In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

C:\Users\ujwal\AppData\Roaming\Python\Python37\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [2]:
from IPython.display import display, HTML
def show_info(data):
    tab_info=pd.DataFrame(data.dtypes).T.rename(index={0:'column type'})
    tab_info=tab_info.append(pd.DataFrame(data.isnull().sum()).T.rename(index={0:'null values (nb)'}))
    tab_info=tab_info.append(pd.DataFrame(data.isnull().sum()/data.shape[0]*100).T.rename(index={0:'null values(%)'}))
    return(display(tab_info))

In [3]:
train = pd.read_csv("Train.csv")
test = pd.read_csv("Test.csv")

In [4]:
train.head()

,grade_A_Component_1,grade_A_Component_2,max_luminosity,thickness,xmin,xmax,ymin,ymax,pixel_area,log_area,x_component_1,x_component_2,x_component_3,x_component_4,x_component_5,class
0,0,1,150,36,144,172,947225,947332,439,439.099273,0,0,1,0,0,1
1,1,0,134,55,1144,1152,2379058,2379624,329,329.205616,1,0,0,0,0,1
2,1,0,135,65,950,974,1038442,1036754,300,300.120598,0,0,0,0,0,2
3,0,1,123,35,41,220,1705580,1705604,6803,6803.778622,0,0,1,0,0,1
4,1,0,138,69,462,466,1088124,1086579,251,251.401943,0,0,0,0,0,2

In [5]:
cols = train.columns.to_list()

In [6]:
cols

['grade_A_Component_1',
 'grade_A_Component_2',
 'max_luminosity',
 'thickness',
 'xmin',
 'xmax',
 'ymin',
 'ymax',
 'pixel_area',
 'log_area',
 'x_component_1',
 'x_component_2',
 'x_component_3',
 'x_component_4',
 'x_component_5',
 'class']

In [7]:
cols.remove('class')

In [10]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1358 entries, 0 to 1357
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   grade_A_Component_1  1358 non-null   int64
 1   grade_A_Component_2  1358 non-null   int64
 2   max_luminosity       1358 non-null   int64
 3   thickness            1358 non-null   int64
 4   xmin                 1358 non-null   int64
 5   xmax                 1358 non-null   int64
 6   ymin                 1358 non-null   int64
 7   ymax                 1358 non-null   int64
 8   pixel_area           1358 non-null   int64
 9   log_area             1358 non-null   float64
 10  x_component_1        1358 non-null   int64
 11  x_component_2        1358 non-null   int64
 12  x_component_3        1358 non-null   int64
 13  x_component_4        1358 non-null   int64
 14  x_component_5        1358 non-null   int64
 15  class                1358 non-null   int64
dtypes: float64(1), int64(15)
memory usage: 169.9 KB

## EDA

In [14]:
train.describe()

,grade_A_Component_1,grade_A_Component_2,max_luminosity,thickness,xmin,xmax,ymin,ymax,pixel_area,log_area,x_component_1,x_component_2,x_component_3,x_component_4,x_component_5,class
count,1358.000000,1358.000000,1358.000000,1358.000000,1358.000000,1358.000000,1.358000e+03,1.358000e+03,1358.000000,1358.000000,1358.000000,1358.000000,1358.000000,1358.000000,1358.000000,1358.000000
mean,0.406480,0.593520,137.893225,78.977909,567.370398,614.032401,1.660107e+06,1.660139e+06,1903.402798,1903.896240,0.081738,0.106038,0.197349,0.035346,0.027982,1.346834
std,0.491357,0.491357,20.480512,55.324842,522.013094,500.505513,1.778153e+06,1.778177e+06,3839.156721,3839.163241,0.274066,0.308000,0.398145,0.184721,0.164983,0.476138
min,0.000000,0.000000,71.000000,35.000000,0.000000,4.000000,7.527000e+03,7.453000e+03,3.000000,3.445293,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,0.000000,0.000000,127.000000,42.000000,53.000000,192.000000,4.662742e+05,4.666918e+05,234.000000,234.335948,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,0.000000,1.000000,137.000000,66.000000,407.500000,457.000000,1.216168e+06,1.214700e+06,346.000000,346.044490,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,1.000000,146.000000,83.000000,1041.750000,1064.000000,2.210012e+06,2.210076e+06,915.250000,915.367817,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
max,1.000000,1.000000,266.000000,305.000000,1692.000000,1717.000000,1.291748e+07,1.291731e+07,37392.000000,37392.672970,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000

In [16]:
x = train.drop('class', axis =1)
y = train['class']

In [21]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(x,y, test_size = 0.3)

###  Modeling

WIthout any normalization/binning

In [15]:
show_info(test)

,grade_A_Component_1,grade_A_Component_2,max_luminosity,thickness,xmin,xmax,ymin,ymax,pixel_area,log_area,x_component_1,x_component_2,x_component_3,x_component_4,x_component_5
column type,int64,int64,int64,int64,int64,int64,int64,int64,int64,float64,int64,int64,int64,int64,int64
null values (nb),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
null values(%),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [32]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import log_loss
from sklearn.metrics import accuracy_score
etc = ExtraTreesClassifier()
etc.fit(x_train,y_train)
y_pred = etc.predict(x_val)
print("Loss: ", log_loss(y_pred, y_val))
print("Accuracy: ", accuracy_score(y_pred, y_val))

Loss:  23.195695641915197
Accuracy:  0.8480392156862745

In [45]:
sub = pd.DataFrame(etc.predict_proba(test))

In [47]:
sub.to_excel("etc_sub1.xlsx", index = False)

In [48]:
sub.shape

(583, 2)

In [49]:
test.shape

(583, 15)